name: VAVOO GUNCELLE
on:
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  vavoo-cek:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Tüm geçmişi çek ki çakışma olmasın
      
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Kütüphaneleri Yukle
        run: pip install requests

      - name: Vavoo Scriptini Calistir
        run: python m3u.py
      
      - name: Git Ayarla ve Kaydet
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git pull --rebase origin main # Çakışmaları otomatik çöz
          git add vavoo.m3u || echo "Dosya bulunamadı"
          git commit -m "Vavoo Listesi Guncellendi" || echo "Degisiklik yok"
          git push origin main
