name: VAVOO GUNCELLE
on:
  schedule:
    - cron: '0 6 * * *' # Her sabah 06:00'da çalışır
  workflow_dispatch:

jobs:
  vavoo-cek:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Çek
        uses: actions/checkout@v4
      
      - name: Python Kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Kütüphaneleri Yukle
        run: pip install requests

      - name: Vavoo Scriptini Calistir
        run: python m3u.py
      
      - name: Git Ayarla ve Kaydet
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add vavoo.m3u
          git commit -m "Vavoo Listesi Guncellendi" || echo "Degisiklik yok"
          git push